spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  liquibase:
    changeLog: classpath:/liquibase/changelog-master.xml